backend:
  name: github
  repo: dehanz13/gatsby-tailwind-coffee-blog
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "index"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: artist
    label: Artist
    folder: content/artist
    create: true
    slug: "index"
    path: "/artist/{{title}}/index"
    editor:
      preview: false
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: album
    label: Album
    folder: content/album
    create: true
    slug: "index"
    path: "/album/{{title}}/index"
    editor:
      preview: false
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
