backend:
  name: github
  repo: dehanz13/gatsby-tailwind-coffee-blog
  branch: master

media_folder: static/assets
public_folder: assets

# slug:
#   encoding: "ascii"
#   clean_accents: true
#   sanitize_replacement: "_"

# collections:
#   - name: blog
#     label: Blog
#     folder: "content/blog"
#     create: true
#     fields:
#       - { name: path, label: Path }
#       - { name: title, label: Title }
#       - { label: "Description", name: "description", widget: "text" }
#       - { name: date, label: Date, widget: datetime }
#       - {
#           name: "featuredpost",
#           label: "Featured Blog",
#           widget: "boolean",
#           default: false,
#         }
#       - { name: body, label: Body, widget: markdown }
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { name: path, label: Path }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          name: "featuredpost",
          label: "Featured Blog",
          widget: "boolean",
          default: false,
        }
      - label: "Thumbnail Image"
        name: "thumbnail"
        widget: image
        choose_url: true
        # default: "/uploads/chocolate-dogecoin.jpg"
        # media_library:
        #   config:
        #     multiple: true
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "product"
    label: "Product"
    folder: "content/product"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "product-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          name: "featuredproduct",
          label: "Featured Blog",
          widget: "boolean",
          default: false,
        }
      - label: "Thumbnail Image"
        name: "thumbnail"
        widget: image
        choose_url: true
        # default: "/uploads/chocolate-dogecoin.jpg"
        # media_library:
        #   config:
        #     multiple: true
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
# - name: artist
#   label: Artist
#   folder: content/artist
#   create: true
#   slug: "index"
#   path: "{{title}}/index"
#   editor:
#     preview: false
#   fields:
#     - { name: title, label: Title, widget: "string" }
#     - { name: "description", label: "Description", widget: "text" }
#     - { name: date, label: Publish Date, widget: datetime }
#     - label: "Thumbnail Image"
#       name: "thumbnail"
#       widget: "image"
#       choose_url: true
#       # default: "/uploads/chocolate-dogecoin.jpg"
#       media_library:
#         config:
#           multiple: true
#     - {
#         name: featured,
#         label: "Featured Blog",
#         widget: "boolean",
#         default: false,
#       }
#     - { name: body, label: Content, widget: markdown }
# - name: album
#   label: Album
#   folder: content/album
#   create: true
#   slug: "index"
#   path: "{{title}}/index"
#   editor:
#     preview: false
#   fields:
#     - { name: title, label: Title, widget: "string" }
#     - { name: "description", label: "Description", widget: "text" }
#     - { name: date, label: Publish Date, widget: datetime }
#     - label: "Thumbnail Image"
#       name: "thumbnail"
#       widget: "image"
#       choose_url: true
#       # default: "/uploads/chocolate-dogecoin.jpg"
#       media_library:
#         config:
#           multiple: true
#     - {
#         name: featured,
#         label: "Featured Blog",
#         widget: "boolean",
#         default: false,
#       }
#     - { name: body, label: Content, widget: markdown }
